---
version: '3'

services:
  registry:
    image: registry:latest
    container_name: registry
    restart: always
    ports:
      - '5000:5000'
    volumes:
      - ./registry:/var/lib/registry
      - ./config/config.yml:/etc/docker/registry/config.yml

  docker-registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: docker-registry-ui
    ports:
      - '8080:80'
    environment:
      - REGISTRY_TITLE=Local Docker Registry
      - REGISTRY_URL=http://localhost:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry

  